title: Lunor
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: garsuslor.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: "https://drive.google.com/uc?id=1bAL0J7J6lPeGD3DLktOffKZiyxBxwIvq"
